In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [21]:
image_path = "frames/panda0.png"
image = mpimg.imread(image_path)
#plt.imshow(image)

In [9]:
from PIL import Image

In [11]:
_a = Image.open(image_path)

In [18]:
_b = _a.convert(mode = 'RGB')

In [20]:
_b.save('frames/prueba.jpg','JPEG', quality = 90, dpi = (300,300))

In [22]:
for ii in range(10):
    image_path = f"frames/panda{ii}"
    _a = Image.open(image_path+".png")
    _b = _a.convert(mode = 'RGB')
    _b.save(image_path+".jpg",'JPEG', quality = 90, dpi = (300,300))

In [7]:
from inspect import signature

def someMethod(self, arg1, *args, kwarg1=None, **kwargs):
    pass

sig = signature(someMethod)

In [8]:
sig

<Signature (self, arg1, *args, kwarg1=None, **kwargs)>

In [9]:
sig.parameters

mappingproxy({'self': <Parameter "self">,
              'arg1': <Parameter "arg1">,
              'args': <Parameter "*args">,
              'kwarg1': <Parameter "kwarg1=None">,
              'kwargs': <Parameter "**kwargs">})

In [1]:
def aaa(a,b):
    c = [a,b]
    def jjj(d):
        print(f'd es {d}, c es {c}')
    return jjj

In [2]:
bb = aaa(1,2)

In [5]:
bb(3)

d es 3, c es [1, 2]


In [4]:
c = 445

In [1]:
c

NameError: name 'c' is not defined

In [1]:
from chords.piecewise import (generate_trapz_m_func, trapz_accel_restr, trapz_mod_accel_restr,
                              hs_accel_restr, hs_mod_accel_restr, generate_hs_m_funcs, hs_half_x,
                             hs_mod_half_x, generate_hs_interp, hs_interp, hs_mod_interp,
                             hs_dot_interp, hs_dot_dot_interp, hs_mod_dot_interp, hs_mod_dot_dot_interp,
                             generate_tz_interp, trap_interp, trap_mod_interp, trap_dot_interp, trap_dot_dot_interp,
                             trap_mod_dot_interp, trap_mod_dot_dot_interp)

In [2]:
from numpy import array

In [3]:
x= array([0.,1,2,3])
x_n = array([3.,4,5,6])
a = array([1.,2])
a_n = array([3.,7])
a_c = array([5.,9])
dt = 0.1
a_m = array([2.,3,1,2])
a_n_m = array([5.,6,3,7])
x_c = hs_half_x(x, x_n, a, a_n, dt)
a_c_m = array([0,0,5.,9])
a_c_m[:2] = x_c[2:]
x_dot = a_m
x_dot_n = a_n_m
x_dot_c = a_c_m
scheme_params = {}

In [4]:
trapz_accel_restr(x, x_n, a, a_n, dt, scheme_params)

array([2.65, 2.55, 2.8 , 2.55])

In [5]:
trapz_mod_accel_restr(x, x_n, a, a_n, dt, scheme_params)

array([2.79166667, 2.68166667, 2.8       , 2.55      ])

In [6]:
tz2 = generate_trapz_m_func(2)

In [7]:
tz2(x, x_n, a, a_n, dt, scheme_params)

array([2.79166667, 2.68166667, 2.8       , 2.55      ])

In [8]:
tz1 = generate_trapz_m_func(1)

In [9]:
tz1(x, x_n, a_m, a_n_m, dt, scheme_params)

array([2.65, 2.55, 2.8 , 2.55])

In [10]:
hs2_half, hs2 = generate_hs_m_funcs(2)

In [11]:
hs2(x, x_n, a, a_n, dt, a_c)

array([2.78166667, 2.66666667, 2.6       , 2.25      ])

In [12]:
hs_mod_accel_restr(x, x_n, a, a_n, dt, a_c)

array([2.78166667, 2.66666667, 2.6       , 2.25      ])

In [13]:
hs2_half(x, x_n, a, a_n, dt)

array([0.12791667, 1.17744792, 3.475     , 4.4375    ])

In [14]:
hs_mod_half_x(x, x_n, a, a_n, dt)

array([0.12791667, 1.17744792, 3.475     , 4.4375    ])

In [15]:
hs1_half, hs1 = generate_hs_m_funcs(1)

In [16]:
hs1(x, x_n, a_m, a_n_m, dt, a_c_m)

array([2.65166667, 2.55416667, 2.6       , 2.25      ])

In [17]:
hs_accel_restr(x, x_n, a, a_n, dt, a_c)

array([2.65166667, 2.55416667, 2.6       , 2.25      ])

In [18]:
hs_half_x(x, x_n, a, a_n, dt)

array([1.4625, 2.4625, 3.475 , 4.4375])

In [19]:
hs1_half(x, x_n, a_m, a_n_m, dt)

array([1.4625, 2.4625, 3.475 , 4.4375])

In [20]:
hs_interp_1  = generate_hs_interp(1)
hs_interp_2  = generate_hs_interp(2)

In [21]:
tau = 0.25
h = 0.5

In [22]:
hs_interp(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c),hs_interp_1(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c)

(array([0.68333333, 1.92708333, 2.875     , 4.5625    ]),
 array([0.68333333, 1.92708333, 2.875     , 4.5625    ]))

In [23]:
hs_mod_interp(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c),hs_interp_2(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c)

(array([0.58854167, 1.90885417, 2.875     , 4.5625    ]),
 array([0.58854167, 1.90885417, 2.875     , 4.5625    ]))

In [24]:
hs_i1_d1 = generate_hs_interp(1, 1)
hs_i1_d2 = generate_hs_interp(1, 2)
hs_i2_d1 = generate_hs_interp(2, 1)
hs_i2_d2 = generate_hs_interp(2, 2)

In [25]:
hs_i1_d1(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c),hs_dot_interp(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c)

(array([3.475 , 4.4375, 5.    , 9.    ]),
 array([3.475 , 4.4375, 5.    , 9.    ]))

In [26]:
hs_i1_d2(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c),hs_dot_dot_interp(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c)

(array([ 6.,  6.,  4., 10.]), array([ 6.,  6.,  4., 10.]))

In [27]:
hs_i2_d1(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c),hs_mod_dot_interp(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c)

(array([2.875 , 4.5625, 5.    , 9.    ]),
 array([2.875 , 4.5625, 5.    , 9.    ]))

In [28]:
hs_i2_d2(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c),hs_mod_dot_dot_interp(x, x_n, x_dot, x_dot_n, tau, h, x_dot_c)

(array([ 5.,  9.,  4., 10.]), array([ 5.,  9.,  4., 10.]))

In [29]:
tz_i1 = generate_tz_interp(1)
tz_i2 = generate_tz_interp(2)
tz_i1_d1 = generate_tz_interp(1, 1)
tz_i1_d2 = generate_tz_interp(1, 2)
tz_i2_d1 = generate_tz_interp(2, 1)
tz_i2_d2 = generate_tz_interp(2, 2)

In [31]:
tz_i1(x, x_n, x_dot, x_dot_n, tau, h), trap_interp(x, x_n, x_dot, x_dot_n, tau, h)

(array([0.6875, 1.9375, 2.375 , 3.8125]),
 array([0.6875, 1.9375, 2.375 , 3.8125]))

In [32]:
tz_i2(x, x_n, x_dot, x_dot_n, tau, h), trap_mod_interp(x, x_n, x_dot, x_dot_n, tau, h)

(array([0.54166667, 1.83854167, 2.375     , 3.8125    ]),
 array([0.54166667, 1.83854167, 2.375     , 3.8125    ]))

In [33]:
tz_i1_d1(x, x_n, x_dot, x_dot_n, tau, h), trap_dot_interp(x, x_n, x_dot, x_dot_n, tau, h)

(array([3.5, 4.5, 2. , 4.5]), array([3.5, 4.5, 2. , 4.5]))

In [34]:
tz_i1_d2(x, x_n, x_dot, x_dot_n, tau, h), trap_dot_dot_interp(x, x_n, x_dot, x_dot_n, tau, h)

(array([ 6.,  6.,  4., 10.]), array([ 6.,  6.,  4., 10.]))

In [35]:
tz_i2_d1(x, x_n, x_dot, x_dot_n, tau, h), trap_mod_dot_interp(x, x_n, x_dot, x_dot_n, tau, h)

(array([2.375 , 3.8125, 2.    , 4.5   ]),
 array([2.375 , 3.8125, 2.    , 4.5   ]))

In [36]:
tz_i2_d2(x, x_n, x_dot, x_dot_n, tau, h), trap_mod_dot_dot_interp(x, x_n, x_dot, x_dot_n, tau, h)

(array([ 2. ,  4.5,  4. , 10. ]), array([ 2. ,  4.5,  4. , 10. ]))